name = "biwor"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = false

[vars]
NODE_ENV = "production"
[[d1_databases]]
binding = "DB"
database_name = "biwor-db"
database_id = "PASTE-YOUR-DATABASE-ID-HERE"
